### PR TITLE
[NXMAPPS-708] removed the protocol flag forcing tcp. Because not all …

### PR DESCRIPTION
**Pull request by codecraftscraic**
…of our locals match, this causes issues for locals that use socket instead of tcp.

### CODE REVIEW

**Comment by bswatson** [comment]
This looks ok to me from a code perspective, but I'd like to know if anyone else has an issue with connecting when taking this out since the default without `--protocol=tcp` would use sockets when the host is `localhost`.

Tagging @stevegrunwell @bradp to confirm.

**Review by stevegrunwell — CHANGES_REQUESTED** [review]
If I'm reading this conditional correctly, the general workflow if this function is:

```sh
# parse DB_HOST for port or socket references
local PARTS=(${DB_HOST//\:/ })
local DB_HOSTNAME=${PARTS[0]};
local DB_SOCK_OR_PORT=${PARTS[1]};
local EXTRA=""
```

Split the `$DB_HOST` parameter on ":" and assign the pre- and post-colon values to `$DB_HOSTNAME` and `$DB_SOCK_OR_PORT`, respectively.

```sh
if ! [ -z $DB_HOSTNAME ] ; then
    if [ $(echo $DB_SOCK_OR_PORT | grep -e '^[0-9]\{1,\}$') ]; then
        EXTRA=" --host=$DB_HOSTNAME --port=$DB_SOCK_OR_PORT --protocol=tcp"
    elif ! [ -z $DB_SOCK_OR_PORT ] ; then
        EXTRA=" --socket=$DB_SOCK_OR_PORT"
    elif ! [ -z $DB_HOSTNAME ] ; then
        EXTRA=" --host=$DB_HOSTNAME --protocol=tcp"
    fi
fi
```

**IF** `$DB_HOSTNAME` is not empty, match whichever condition is satisfied first:

...**AND** `$DB_SOCK_OR_PORT` is purely numeric (Path 1):
Assume this is a port number and specify a TCP/IP connection to MySQL

...**AND** `$DB_SOCK_OR_PORT` is not empty (Path 2):
Assume this is a socket connection

...**AND** `$DB_HOSTNAME` is (still) not empty (this should really be an "else" clause) (Path 3):
Assume the hostname is all that's needed

In practice, this would indicate the following:

| `$DB_HOST` | `$EXTRA` | Path # |
| --- | --- | --- |
| `localhost` | `--host=localhost --protocol=tcp` | 3 |
| `localhost:3306` | `--host=localhost --port=3306 --protocol=tcp` | 1 |
| `db.example.com` | `--host=db.example.com --protocol=tcp` | 3 |
| `db.example.com:3306` | `--host=db.example.com --port=3306 --protocol=tcp` | 1 |
| `/tmp/mysql.sock` | `--socket=/tmp/mysql.sock` | 2 |

```sh
# create database
if [ $(mysql --user="$DB_USER" --password="$DB_PASS"$EXTRA --execute='show databases;' | grep ^$DB_NAME$) ]
then
    echo "Reinstalling will delete the existing test database ($DB_NAME)"
    read -p 'Are you sure you want to proceed? [y/N]: ' DELETE_EXISTING_DB
    recreate_db $DELETE_EXISTING_DB
else
    create_db
fi
```

Connect to MySQL using the given credentials + connection configuration to see if the database already exists and, if it does, re-create it (after prompting); otherwise, move forward creating the database.

All this in mind, it seems like it may be an issue with how the script is being invoked locally rather than an issue with the script itself. In an environment that requires sockets to connect to MySQL, I'd expect the call to this script to look something like:

```sh
# Assuming root/root for the local MySQL server.
$ install-wp-tests.sh wordpress_test root root /tmp/mysql.sock
```

**Comment by codecraftscraic** [comment]
> All this in mind, it seems like it may be an issue with how the script is being invoked locally rather than an issue with the script itself. In an environment that requires sockets to connect to MySQL, I'd expect the call to this script to look something like:
> 
> ```shell
> # Assuming root/root for the local MySQL server.
> $ install-wp-tests.sh wordpress_test root root /tmp/mysql.sock
> ```

The problem with invoking it like that is that localwp states a very long path that is not cli friendly for the socket.  For example 

`/Users/username/Library/Application Support/Local/run/DeksEpSrR/mysql/mysqld.sock`

I'm going to remove the tests and the assertwell folder and redo the install with the tcp flag back in, to see if it we missed something else.

**Comment by stevegrunwell** [comment]
> `/Users/username/Library/Application Support/Local/run/DeksEpSrR/mysql/mysqld.sock`

You'll definitely want to wrap that in quotes, as the space will break the arguments. Curse you, macOS and your user-friendly path names! ::shakes fist::

**Comment by codecraftscraic** [comment]
> > `/Users/username/Library/Application Support/Local/run/DeksEpSrR/mysql/mysqld.sock`
> 
> You'll definitely want to wrap that in quotes, as the space will break the arguments. Curse you, macOS and your user-friendly path names! ::shakes fist::

We tried that as well during our debugging session (both single and double quotes, it still breaks at the space in Application Support), but the script wasn't processing the socket correctly and threw a different error that asked for me to be sure that mysqld was running, which we know it was from previous connection attempts in the cli.

**Comment by codecraftscraic** [comment]
And I can confirm that with the tcp specification, it isn't working to install my tests locally.

**Comment by codecraftscraic** [comment]
After much discussion, we have decided not to move forward with this step and pursue other options for fixing the mental load of the local issues.

**Pull request closed without merging**
